version: "3.9"
services:
  db_postgres:
    depends_on:
      - droog   
    container_name: postgres_container
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "frienddb"
      POSTGRES_USER: "friend-service"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U friend-service -d frienddb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: docker-pg   
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  droog:
    container_name: droog_container
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        tag: docker-droog     
    environment:
      - DbPass=qwerty
    ports:
      - 1080:8080
 
    
     